# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            AJS
tagline:          'The Digital Home of Aaron James Smith'
description:      ''
url:              http://slapula.github.io
baseurl:          /

author:
  name:           'Aaron Smith'

paginate:         5

# Custom vars
version:          2.1.0
gems:             [jekyll-paginate]

github:
  repo:           https://github.com/slapula

kramdown:
  input:          GFM
