# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            AJS
tagline:          'The Digital Home of Aaron James Smith'
description:      'smithbot.com'
url:              http://slapula.github.io
baseurl:          /

author:
  name:           'Aaron Smith'

paginate:         5

# Custom vars
version:          2.1.0
gems:             [jekyll-paginate]

github:
  repo:           https://github.com/slapula

linkedin:         https://www.linkedin.com/in/aaron-smith-1661a95

kramdown:
  input:          GFM

slider_array:     []
